### ISSUE TITLE
Add Currency Conversion

### ISSUE THREAD

**Issue by willm30** [JoinColony/colonyCDapp#1552]
This can be done after the beta launch.

This adds the ability for users to be able to display converted currencies in the DApp in the currency that they would like. It is an option that is available for the main user dropdown menu. This required us finding a suitable 3rd party API service suitable for getting the conversion to work as required for the supported currencies.

One great bonus would be able to auto detect a users location and if no preference is set for for their preferred currency, we show the our best guess based on location.

The fallback would be to show values in USD.

Supported currencies:

- **USD** - United States Dollar
- **JPY** - Japanese Yen
- **CAD** - Canadian Dollar
- **KRW** - South Korean Won
- **EUR** - Euro
- **INR** - Indian Rupee
- **GBP** - British Pound Sterling
- **BRL** - Brazilian Real
- **ETH** - Ethereum
- **CLNY** - Colony Network Token

Design: https://www.figma.com/file/5V8pr7iMwXsT9L3VAZsmUt/Colony-V5?type=design&node-id=9707%3A60973&mode=design&t=zNJdFiglhEoGd2Lw-1

![image](https://github.com/JoinColony/colonyCDapp/assets/64402732/0ae64c31-96af-4f3c-b895-a2c097556fc0)

![image](https://github.com/JoinColony/colonyCDapp/assets/64402732/54b91923-c01a-4dc3-91ec-24e98a15b3b8)

Done when:
- [x] There is a UI component in the user menu that allows a user to express a currency preference  #1572
- [x] There is a util function that can fetch the conversion from a given token to a given currency/token #1565
- [x] User location is auto detected and if no preference is set for their preferred currency, we show our best guess based on location. #1594 

For separate issue:

- [x] #1623

**Comment by rdig** [comment]
@willm30 is this Issues still relevant? b/c as far as I can see, _(and other than the #1717 bug)_ everything else that composes this feature was implemented.

That makes me say that this should now be considered complete.

Thank you for your work! 🥃

**Comment by rdig** [comment]
Since now [#1717](https://github.com/JoinColony/colonyCDapp/issues/1717) has been merged, this issue is now complete and I will close it out.

Thank you again for your work here @willm30  _(and @iamsamgibbs)_
