### ISSUE TITLE
[`ActionSidebar` refactor] Remove agreement drafts from redux store

### ISSUE THREAD

**Issue by chmanie** [JoinColony/colonyCDapp#2829]
### Description

During the `ActionSidebar` refactor, as we are retiring redux anyways (in the far future but nevertheless), we should remove the drafts from the redux store and put it onto the database or localStorage entirely (_not_ a combination of both, discuss with the team).

See here for an example of how it's currently used:

### This issue is complete when...

- [ ]

### Suggestions (optional)

* Example: It's probably a good idea to keep the transaction state separate from other async actions that relate to them; i.e. either adding an extra transaction status, or keeping the transaction as `PENDING` while other async activity finishes would probably lead to some confusion and unintended side effects. Perhaps component state would be a more suitable starting point.

### Subtasks (optional)

- [ ] Create a prop (e.g. with component state) which indicates either a transaction is pending, or async activity is in progress related to that transaction, in the context of the wizard
- [ ] Pass down a prop to the `TransactionStatus` component
- [ ] Adjust the `TransactionStatus` component such that it shows the indicator with the given prop
