### ISSUE TITLE
Notifications: Mark as read

### ISSUE THREAD

**Issue by davecreaser** [JoinColony/colonyCDapp#3009]
### Story

As a *user reading notifications*, I want to *be able to mark notifications as read*, so that *I can keep track of which notifications are fresh*

** TODO: Fill out below **

### Description

Example: During the colony creation wizard, there is an activity indicator for pending transactions, but there is no indicator of other async operations (e.g. for the DDB) in between these transactions. It's important that the indicator remains visible until all async activity is finished, because otherwise the user has no feedback that they're waiting for something to finish; they might leave the wizard or refresh the page, leading to frustration.

### Design

[Figma link](https://the-link-to-the-design-on-figma)

[Image](!https://inline-image-from-figma-for-quick-reference-or-posterity)

### This issue is complete when...

- [ ] The activity indicator for the `TransactionStatus` component is shown during any and all async waiting
- [ ] The indicator is hidden when async waiting finishes (either successfully or unsuccessfully)

### Suggestions (optional)

* Example: It's probably a good idea to keep the transaction state separate from other async actions that relate to them; i.e. either adding an extra transaction status, or keeping the transaction as `PENDING` while other async activity finishes would probably lead to some confusion and unintended side effects. Perhaps component state would be a more suitable starting point.

### Subtasks (optional)

- [ ] Create a prop (e.g. with component state) which indicates either a transaction is pending, or async activity is in progress related to that transaction, in the context of the wizard
- [ ] Pass down a prop to the `TransactionStatus` component
- [ ] Adjust the `TransactionStatus` component such that it shows the indicator with the given prop

**Comment by iamsamgibbs** [comment]
Started working on this thinking it was just "Mark all as read" - will create a PR that contributes to that part of this issue.

**Comment by iamsamgibbs** [comment]
"Mark all as read" is completed by #3066

The rest of this issue is blocked #3007
