### ISSUE TITLE
[Proxy colonies M1] feat: handle reenabling of a proxy colony

### ISSUE THREAD

**Issue by bassgeta** [JoinColony/colonyCDapp#3457]
### Story

As a *user moderating a colony*, I want to *"add" a new proxy colony which has been previously removed*.

### Description

Since we don't remove proxy colonies, but we just disable them in the database, we need to create a new transaction for this which isn't going to call the `createProxyColony` contract, but probably an `editColonyByDelta` contract to reenable that proxy colony.
**TODO** check if it's going to be a problem creating actions of the same type but with different underlying contracts, shouldn't be an issue but you never know

### This issue is complete when...

- [x] Reenabling a proxy colony works
- [x] Reenabling via voting reputation works
- [x] Reenabling via multisig works

### Suggestions (optional)

* Example: It's probably a good idea to keep the transaction state separate from other async actions that relate to them; i.e. either adding an extra transaction status, or keeping the transaction as `PENDING` while other async activity finishes would probably lead to some confusion and unintended side effects. Perhaps component state would be a more suitable starting point.

### Subtasks (optional)

- [ ] Create a prop (e.g. with component state) which indicates either a transaction is pending, or async activity is in progress related to that transaction, in the context of the wizard
- [ ] Pass down a prop to the `TransactionStatus` component
- [ ] Adjust the `TransactionStatus` component such that it shows the indicator with the given prop

**Comment by rumzledz** [comment]
After discussing this task yesterday with @bassgeta and @davecreaser , I'll assign myself the task of disabling and re-enabling proxy colonies via motion 👌

**Comment by rumzledz** [comment]
I've had a chat with @davecreaser and I'll be doing the multi-sig part for enabling and disabling proxy colonies
