### ISSUE TITLE
Port mobile styles for Colony Home

### ISSUE THREAD

**Issue by willm30** [JoinColony/colonyCDapp#99]
Currently, colony home page isn't mobile repsonsive like in the dapp. These styles should be ported over. 

Related components that should also have their styles brought across:

- [x] Colony Home handled in #101 
- [x] UserNavigation handled in #101
- [x] SubscribedColonies Dropdown handled in #136 
- [x] ColonyTotalFunds
